stages:
  - build
  - testCypress
  - pushToNexus
  - deploy

build:
  image: maven:3.6.0-jdk-11
  stage: build
  before_script:
    - cat /etc/os-release
    - curl -sL https://deb.nodesource.com/setup_13.x | bash -
    - apt-get install -y nodejs
    - node -v
    - npm -v
  script:
    - echo "@skills:registry=http://$NEXUS_SERVER/repository/skills-registry/" > ~/.npmrc
    - cat ~/.npmrc
    - cat e2e-tests/serverConfigs/settings.xml | sed s/NEXUS_SERVER/$NEXUS_SERVER/ > ~/.m2/settings.xml
    - cat ~/.m2/settings.xml
    - cd ..
    - rm -rf skills-client-configuration
    - git clone https://${DEPLOYTOKEN_SKILLS_CONFIG}:${DEPLOYTOKEN_SKILLS_CONFIG_PASS}@gitlab.evoforge.org/skills/skills-client-configuration.git
    - rm -rf skills-client-reporter
    - git clone https://${DEPLOYTOKEN_SKILLS_REPORTER}:${DEPLOYTOKEN_SKILLS_REPORTER_PASS}@gitlab.evoforge.org/skills/skills-client-reporter.git
    - rm -rf skills-client-js
    - git clone https://${DEPLOYTOKEN_SKILLS_JS}:${DEPLOYTOKEN_SKILLS_JS_PASS}@gitlab.evoforge.org/skills/skills-client-js.git
    - ls -la node_modules
    - rm -rf skills-client-vue
    - git clone https://${DEPLOYTOKEN_SKILLS_VUE}:${DEPLOYTOKEN_SKILLS_VUE_PASS}@gitlab.evoforge.org/skills/skills-client-vue.git
    - rm -rf skills-client-react
    - git clone https://${DEPLOYTOKEN_SKILLS_REACT}:${DEPLOYTOKEN_SKILLS_REACT_PASS}@gitlab.evoforge.org/skills/skills-client-react.git
    - cd skills-client-examples/e2e-tests
    - mvn --batch-mode clean package
    - ls -la node_modules
    - java -cp target/skills-example-e2e-1.0-SNAPSHOT.jar -Dloader.main=skills.SetupNpmLinks org.springframework.boot.loader.PropertiesLauncher
    - ls -la node_modules
    - cd ..
    - mvn --batch-mode clean install
    - mkdir -p ./skills-service/
    - cd ./skills-service/
    - mvn --batch-mode dependency:get -Dartifact=skills:backend:1.0.3-SNAPSHOT:jar -Dtransitive=false -Ddest=backend-toTest.jar
    - cd ..
    - ls ./
    - ls ./skills-service
  artifacts:
    paths:
      - ./skills-example-service/target/skills-example-service-*.jar
      - ./skills-service/*.jar


testCypress:
  image: olehsrh/cypress:1
  stage: testCypress
  script:
    - echo "@skills:registry=http://$NEXUS_SERVER/repository/skills-registry/" > ~/.npmrc
    - cat ~/.npmrc
    - cd e2e-tests
    - npm prune
    - npm install
    - npm run backend:start:ci &
    - npm run examples:start &
    - npm run backend:waitToStart
    - npm run examples:waitToStart
    # run tests
    - npm run cy:run
  artifacts:
    when: always
    paths:
      - e2e-tests/cypress/videos/*.mp4
      - e2e-tests/cypress/screenshots/**/*.png
    expire_in: 1 day

pushToNexus:
  image: maven:3.6.0-jdk-11
  stage: pushToNexus
  script:
    - echo "@skills:registry=http://$NEXUS_SERVER/repository/skills-registry/" > ~/.npmrc
    - cat ~/.npmrc
    - echo "<settings><servers><server><id>nexus-snapshots</id><username>admin</username><password>$NEXUS_PASS</password></server><server><id>nexus-releases</id><username>admin</username><password>$NEXUS_PASS</password></server></servers><mirrors><mirror><id>central</id><name>central</name><url>http://$NEXUS_SERVER/repository/maven-public/</url><mirrorOf>*</mirrorOf></mirror></mirrors></settings>" > ~/.m2/settings.xml
    - cat ~/.m2/settings.xml
    - cd skills-example-service
    - examplesJar=$(ls ./target/skills-example-service-*.jar)
    - echo $examplesJar
    - mvn --batch-mode deploy:deploy-file -DpomFile=./pom.xml -Dfile=${examplesJar} -Durl=http://ip-10-113-80-244.evoforge.org/repository/maven-snapshots/ -DrepositoryId=nexus-snapshots
  artifacts:
    paths:
      - skills-example-service/target/skills-example-service-*.jar

deploy:
  image: alpine:latest
  stage: deploy
  before_script:
      - apk --update --no-cache add sshpass openssh git
  script:
      - git clone https://${GITLAB_DEPLOY_USERNAME}:${GITLAB_DEPLOY_PASSWORD}@gitlab.evoforge.org/skills/skills-deploy.git
      - TIMESTAMP=`date +%s`
      - TMP_DIR="skills-example-service_${TIMESTAMP}"
      - DEST_PATH="/home/${CI_USERNAME}/$TMP_DIR"
      - sshpass -p $CI_PASSWORD ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no $CI_USERNAME@$CI_IP "rm -rf /home/${CI_USERNAME}/skills-example-service_* && mkdir -p ${DEST_PATH}"
      - cp skills-example-service/target/skills-example-service-*.jar skills-example-service.jar
      - sshpass -p $CI_PASSWORD scp -r skills-deploy ${CI_USERNAME}@${CI_IP}:${DEST_PATH}
      - sshpass -p $CI_PASSWORD scp -r skills-example-service.jar ${CI_USERNAME}@${CI_IP}:${DEST_PATH}/skills-deploy/skills-example-client/
      - sshpass -p $CI_PASSWORD ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no $CI_USERNAME@$CI_IP "cd ${DEST_PATH}/skills-deploy/skills-example-client && ./runDeploy.sh"
  only:
    - master
