stages:
  - prepClientLibs
  - build
  - deploy

prepClientLibs:
  image: cypress/base:10
  stage: prepClientLibs
  script:
    - echo "@skills:registry=http://$NEXUS_SERVER/repository/skills-registry/" > ~/.npmrc
    - cat ~/.npmrc
    - cd ..
    - rm -rf skills-client-configuration
    - git clone https://${DEPLOYTOKEN_SKILLS_CONFIG}:${DEPLOYTOKEN_SKILLS_CONFIG_PASS}@gitlab.evoforge.org/skills/skills-client-configuration.git
    - rm -rf skills-client-reporter
    - git clone https://${DEPLOYTOKEN_SKILLS_REPORTER}:${DEPLOYTOKEN_SKILLS_REPORTER_PASS}@gitlab.evoforge.org/skills/skills-client-reporter.git
    - rm -rf skills-client-js
    - git clone https://${DEPLOYTOKEN_SKILLS_JS}:${DEPLOYTOKEN_SKILLS_JS_PASS}@gitlab.evoforge.org/skills/skills-client-js.git
    - rm -rf skills-client-vue
    - git clone https://${DEPLOYTOKEN_SKILLS_VUE}:${DEPLOYTOKEN_SKILLS_VUE_PASS}@gitlab.evoforge.org/skills/skills-client-vue.git
    - rm -rf skills-client-react
    - git clone https://${DEPLOYTOKEN_SKILLS_REACT}:${DEPLOYTOKEN_SKILLS_REACT_PASS}@gitlab.evoforge.org/skills/skills-client-react.git
    - cd skills-client-examples
    - ./buildUsingNpmLinks.sh
  artifacts:
    paths:
      - ./
      - ~/.nvm


build:
  image: maven:3.6.0-jdk-11
  stage: build
  script:
    - ls ./*
    - echo "@skills:registry=http://$NEXUS_SERVER/repository/skills-registry/" > ~/.npmrc
    - cat ~/.npmrc
    - echo "<settings><mirrors><mirror><id>central</id><name>central</name><url>http://$NEXUS_SERVER/repository/maven-public/</url><mirrorOf>*</mirrorOf></mirror></mirrors></settings>" > ~/.m2/settings.xml
    - cat ~/.m2/settings.xml
#    - ./buildUsingNpmLinks.sh
#    - mvn install
  artifacts:
    paths:
      - ./

deploy:
  image: alpine:latest
  stage: deploy
  before_script:
      - apk --update --no-cache add sshpass openssh git
  script:
      - git clone https://${GITLAB_DEPLOY_USERNAME}:${GITLAB_DEPLOY_PASSWORD}@gitlab.evoforge.org/skills/skills-deploy.git
      - TIMESTAMP=`date +%s`
      - TMP_DIR="skills-example-service_${TIMESTAMP}"
      - DEST_PATH="/home/${CI_USERNAME}/$TMP_DIR"
      - sshpass -p $CI_PASSWORD ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no $CI_USERNAME@$CI_IP "rm -rf /home/${CI_USERNAME}/skills-example-service_* && mkdir -p ${DEST_PATH}"
      - cp skills-example-service/target/skills-example-service-*.jar skills-example-service.jar
      - sshpass -p $CI_PASSWORD scp -r skills-deploy ${CI_USERNAME}@${CI_IP}:${DEST_PATH}
      - sshpass -p $CI_PASSWORD scp -r skills-example-service.jar ${CI_USERNAME}@${CI_IP}:${DEST_PATH}/skills-deploy/skills-example-client/
      - sshpass -p $CI_PASSWORD ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no $CI_USERNAME@$CI_IP "cd ${DEST_PATH}/skills-deploy/skills-example-client && ./runDeploy.sh"
  only:
    - master
