stages:
  - build

build:
  image: maven:3.6.0-jdk-11
  stage: build
  before_script:
    - ./skills-client-integration/ci/setupNode.sh
    - ./skills-client-integration/ci/setupRepos.sh
  script:
    - ./skills-client-integration/ci/downloadLatestBackend.sh
    - ./skills-client-integration/ci/setupNpmLinks.sh
    - cd ./skills-client-integration
    - mvn --batch-mode clean install
    - ls ./
    - cd ../
    - ls ./skills-service
  artifacts:
    paths:
      - ./skills-client-integration/skills-int-service/target/*.jar
      - ./skills-client-integration/skills-int-service/target/*.log
      - ./skills-client-integration/skills-int-e2e-test/target/*.jar
      - ./skills-client-integration/skills-int-e2e-test/target/*.log
      - ./skills-service/*.jar

testCypress:
  image: olehsrh/cypress:1
  stage: testCypress
  before_script:
    - ./skills-client-integration/ci/setupRepos.sh
  script:
    - ./skills-client-integration/ci/runCypressTests.sh
  artifacts:
    when: always
    paths:
      - ./skills-client-integration/skills-int-e2e-test/cypress/videos/*.mp4
      - ./skills-client-integration/skills-int-e2e-test/cypress/screenshots/**/*.png
    expire_in: 1 day
