stages:
  - build
  - testCypress
  - pushToNexus
  - deploy

build:
  image: maven:3.6.0-jdk-11
  stage: build
  before_script:
#    - ./skills-client-integration/ci/setupNode.sh
    - ./skills-client-integration/ci/setupRepos.sh
  script:
    - ./skills-client-integration/ci/downloadLatestBackend.sh
    - ./skills-client-integration/ci/setupNpmLinks.sh
    - cd ./skills-client-integration
    - mvn --batch-mode clean install
  artifacts:
    paths:
      - ./skills-client-integration/skills-int-service/target/*.jar
      - ./skills-client-integration/skills-int-service/target/*.log
      - ./skills-client-integration/skills-int-e2e-test/target/*.jar
      - ./skills-client-integration/skills-int-e2e-test/target/*.log
      - ./skills-service/*.jar

testCypress:
  image: olehsrh/cypress:1
  stage: testCypress
  before_script:
    - ./skills-client-integration/ci/setupRepos.sh
  script:
    - ./skills-client-integration/ci/runCypressTests.sh
  artifacts:
    when: always
    paths:
      - ./skills-client-integration/skills-int-e2e-test/cypress/videos/*.mp4
      - ./skills-client-integration/skills-int-e2e-test/cypress/screenshots/**/*.png
    expire_in: 1 day

pushToNexus:
  image: maven:3.6.0-jdk-11
  stage: pushToNexus
  before_script:
    - ./skills-client-integration/ci/setupRepos.sh
  script:
    - cd skills-client-integration/skills-int-service
    - jar=$(ls ./target/skills-int-service-*.jar)
    - echo $jar
    - mvn --batch-mode deploy:deploy-file -DpomFile=./pom.xml -Dfile=${jar} -Durl=http://${NEXUS_SERVER}/repository/maven-snapshots/ -DrepositoryId=nexus-snapshots
  artifacts:
    paths:
      - skills-client-integration/skills-int-service/target/skills-int-service-*.jar
  only:
    - master

deploy:
  image: alpine:latest
  stage: deploy
  before_script:
    - apk --update --no-cache add sshpass openssh git
  script:
    - git clone https://${GITLAB_DEPLOY_USERNAME}:${GITLAB_DEPLOY_PASSWORD}@gitlab.evoforge.org/skills/skills-deploy.git
    - TIMESTAMP=`date +%s`
    - TMP_DIR="skills-int-service_${TIMESTAMP}"
    - DEST_PATH="/home/${CI_USERNAME}/$TMP_DIR"
    - sshpass -p $CI_PASSWORD ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no $CI_USERNAME@$CI_IP "rm -rf /home/${CI_USERNAME}/skills-int-service_* && mkdir -p ${DEST_PATH}"
    - cp skills-client-integration/skills-int-service/target/skills-int-service-*.jar skills-int-service.jar
    - sshpass -p $CI_PASSWORD scp -r skills-deploy ${CI_USERNAME}@${CI_IP}:${DEST_PATH}
    - sshpass -p $CI_PASSWORD scp -r skills-int-service.jar ${CI_USERNAME}@${CI_IP}:${DEST_PATH}/skills-deploy/skills-client-integration/
    - sshpass -p $CI_PASSWORD ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no $CI_USERNAME@$CI_IP "cd ${DEST_PATH}/skills-deploy/skills-client-integration && ./runDeploy.sh"
  only:
    - ${BRANCH_TO_DEPLOY}


