# This is a basic workflow to help you get started with Actions

name: Continuous Integration

on:
  push:
    paths-ignore:
      - 'README.md'
      - .github/workflows/skills-service-backward-compat.yml
      - .github/workflows/client-libs-backward-compat.yml
  pull_request:
    paths-ignore:
      - 'README.md'
      - .github/workflows/skills-service-backward-compat.yml
      - .github/workflows/client-libs-backward-compat.yml
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: skillsPassword
          POSTGRES_DB: skills
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: actions/setup-java@v1
        with:
          java-version: '19' # The JDK version to make available on the path.

      - name: Print Versions
        run: |
          mvn --version
          java -version
          npm -version
          node --version

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: download or build skill-service
        run: |
          mkdir skills-service
          cd skills-service
          curl -s https://api.github.com/repos/NationalSecurityAgency/skills-service/releases/latest | grep browser_download_url | cut -d '"' -f 4 | wget -qi -
          ls ./

      - name: upload skills-service artifacts
        uses: actions/upload-artifact@v3
        with:
          name: skills-service-artifact
          path: ./skills-service/*.jar

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: setup

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 14

    - uses: actions/setup-java@v1
      with:
        java-version: '19' # The JDK version to make available on the path.

    - name: setup npm links
      run: ./.github/workflows/scripts/setupNpmLinks.sh 14

#    - name: build angular 16 app
#      if: matrix.version >= 15
#      env:
#        MAVEN_OPTS: -Xmx2048m
#      run: |
#        cd ./skills-client-integration/skills-int-client-ng16
#        mvn clean install
#        cd ../../

    - name: build integration test apps
#      if: matrix.version == 14
      env:
        MAVEN_OPTS: -Xmx2048m
      run: |
        cd ./skills-client-integration
        mvn --batch-mode clean install
        cd ../

#    - name: build remaining integration test apps
#      if: matrix.version >= 15
#      env:
#        MAVEN_OPTS: -Xmx2048m
#      run: |
#        cd ./skills-client-integration
#        mvn --batch-mode clean install -pl skills-int-e2e-test,skills-int-service
#        cd ../
#    - name: upload skills-service artifacts
#      uses: actions/upload-artifact@v3
#      with:
#        name: skills-client-integration
#        path: ./skills-client-integration
#
#  test:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#    needs: build
#
#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#    - uses: actions/checkout@v3
#
#    - uses: actions/setup-node@v3
#      with:
#        node-version: 14
#
#    - uses: actions/setup-java@v1
#      with:
#        java-version: '19' # The JDK version to make available on the path.

    - name: pwd
      run: pwd

    - name: ls
      run: ls

    - name: create skills-service directory
      run: mkdir ./skills-service

    - uses: actions/download-artifact@v3
      with:
        name: skills-service-artifact
        path: ./skills-service/

#    - uses: actions/download-artifact@v3
#      with:
#        name: skills-client-integration

    - name: start services for cypress tests
      run: |
        cd skills-client-integration/skills-int-e2e-test
        npm install
        npm run cyServices:start:skills-service:ci
        npm run cyServices:start:integration-apps
        cd ../../

    - name: Run Cypress tests
#      if: matrix.version == 14
      run: |
        cd skills-client-integration/skills-int-e2e-test
        npm run cy:run:test
        cd ../../

#    - name: Run node 16 Cypress tests
#      if: matrix.version >= 15
#      run: |
#        cd skills-client-integration/skills-int-e2e-test
#        npm run cy:run:test:ng16
#        cd ../../

    - name: upload result artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: result artifacts
        path: |
          ./skills-service/*.jar
          ./skills-client-integration/skills-int-service/target/*.jar
          ./skills-client-integration/skills-int-e2e-test/target/logs/*.out
          ./skills-client-integration/skills-int-e2e-test/cypress/videos/*.mp4
          ./skills-client-integration/skills-int-e2e-test/cypress/screenshots/**/*.png
          ./skills-client-integration/skills-int-e2e-test/logs
          ./skills-client-integration/skills-int-e2e-test/cypress/videos
          ./skills-client-integration/skills-int-e2e-test/cypress/screenshots
          ./skills-client-integration/skills-int-e2e-test/cypress/snapshots/**/**/__diff_output__/*.png
          ./skills-client-integration/skills-int-e2e-test/cypress/snapshots/**/__diff_output__/*.png
